
import subprocess
import time


DEFAULT_PROMPTS = [
    "robot with multi-colored neon stripes",
    "dark brown hockey stick with black tape",
    "streamlined red turbine base",
    "metallic griffin holding golden treasure chest tightly",
    "yellow textured triangular pencil holder",
    "teal fabric scissors with curved blades",
    "jagged obsidian rock darkly reflecting light",
    "glossy white compact robot model",
    "tall white vase with fresh flowers in it",
    "shiny white crystal with iridescent colors",
    "pink heart-shaped toadstool in woods",
    "iridescent gold griffin standing proud",
    "platinum earring sparkles faintly",
    "vintage doll with curly hair twirling around",
    "glossy purple grape bunch on stem",
    "jade bangle with mother of pearl inlay",
    "sleek carbon fiber black race car",
    "smooth white frothy milk pitcher",
    "sleek violet mermaid in starlight gown",
    "tiny square white and black opal bracelet",
    "gold chisel with chips in it",
    "clear cylindrical citrine with sunny yellow shade",
    "navy blue soccer cleats studs",
    "green four-eyed robot holding tool",
    "spaceship carries booster rockets",
    "sophisticated pearl tiara with subtle curves",
    "onyx flat broadsword",
    "gold-plated action figure with dynamic pose",
    "robot with white square body and blue round head",
    "glossy emerald obelisk-shaped gem",
    "sleek black robot beside plant pot",
    "smooth green pear perched atop white napkin",
    "vintage steel drum adorned with tropical designs",
    "white cotton ball nestled in wooden bowl",
    "long bench made of metal",
    "small curved wooden tool",
    "large yellow diamond with chip in it",
    "multi-colored beads on leather string",
    "purple frisbee aerodynamic and disc-shaped",
    "purple synthetic track shoe",
    "matte-black humanoid robot standing in pose of contemplation",
    "pinecone on blue spruce branch",
    "tiny wand wrapped in velvet ribbon",
    "minimalist clear plastic protractor",
    "red vanity mirror",
    "glossy yellow fruit bowl deep rimmed",
    "opal necklace with sun shape",
    "blue monkey with yellow face",
    "elegant pearl pendant on dainty chain",
    "warm brown mug of hot chocolate",
    "wizards cloak with golden trim",
    "metallic green bow with polished wood limbs",
    "prismatic violet tourmaline glows",
    "sniper rifle custom scope with infrared capabilities",
    "gray squirrel running briskly",
    "beige robot holding wrench",
    "giant red centaur holding shield",
    "dagger with ivory handle and golden tip",
    "powerful purple hippogriff in fierce battle stance",
    "vibrant blue feathered phoenix wings spread standing proud on marble pedestal",
    "metallic cylinder with rounded edges",
    "metal carving tool set",
    "elegant gold ring featuring sapphire centerpiece",
    "lustrous white opal shard",
    "mortar tube loaded ready for launch",
    "compact green bamboo cabinet",
    "donut with flames",
    "clay pot with rim chips",
    "colorful macaron set on silver tray",
    "silvery-white robot embodying modern simplicity",
    "colorful kaleidoscope-shaped glass ornament",
    "artillery piece in sandbags",
    "translucent hexagonal quartz piece in pale yellow tone",
    "tall purple plastic spaceship",
    "smooth brown obsidian bracelet",
    "azure yellow mushroom",
    "table tennis paddle with red surface",
    "smooth purple robot adorned with golden symbols",
    "iridescent purple crystal pointed tip",
    "ornamental ivory horned helmet",
    "purple felt puzzle piece",
    "grey lamp with pink stripes",
    "blue earring with leaf-shaped stone",
    "heart-shaped pendant in gold",
    "opal brooch with alligator clip closure",
    "greek bowl painted with red and black figures",
    "brown dagger with ebony tip",
    "glossy blue baseball bat with engraved logo",
    "stone elephant tusks curved in tranquil pose",
    "robot wearing red sphere",
    "platinum bullet casing",
    "tiny robot in pink overalls",
    "large wooden shelf with candles and tea lights",
    "black goblet with runes",
    "gold choker with heart-shaped pendant",
    "polished titanium fishing hook",
    "lavender-hued cupcake with swirl pattern",
    "green robot in star pose",
    "pear-shaped milky opal with iridescent glow",
    "turquoise android robot with expressive face",
    "cup brimming with frothy minty mojito",
    "high-tech explorer ship equipped with scanning lasers",
    "glossy emerald gemstone carved into oval shape",
    "pleated khaki pants wide leg fit",
    "model airplane red and white striped",
    "measuring tape coiled",
    "lustered gold topaz prism",
    "wide and tall wooden table with two chairs on either side of it",
    "jet-black robot with smooth surfaces",
    "gold band with star pattern",
    "dull grey rusty scimitar with jagged edge",
    "glossy gold cylindrical bot balanced on its side",
    "silver tongs on countertop",
    "yellow cylindrical shield",
    "metallic droid featuring polished gold finish",
    "orange peeler placed beside bowl",
    "cyan hovercraft with inflatable pontoons and canopy",
    "white oven mitt hanging from handle",
    "silk gloves white soft touch",
    "sapphire shell encasing golden cyborg heart",
    "silvery white trapezoidal robot",
    "blue dragon with grey horns",
    "plastic bucket holding gardening tools",
    "opal ring featuring swirling pattern",
    "purple orb embedded with stars",
    "tall vase with long stem and wide base",
    "phoenician amphora painted with seafaring scenes",
    "goblin wielding rusted curved sword",
    "goblin with mischievous grin red cap",
    "sleek curved knife in black",
    "polished scissors in metal stand",
    "elegant volleyball uniform style",
    "modern glass vase holding single white lily bloom",
    "statue of lion made of ceramic",
    "gold-plated robot with octagonal head",
    "turquoise spherical drone robot",
    "wooden saw with sharp blade and handle for gripping",
    "futuristic black shuttle with transparent cockpit windows",
    "sturdy dahlia flower with petals in gradient hues",
    "standing angel in gold and white",
    "roman amphora wide mouthed",
    "heavy-duty leatherwork awl",
    "mortar launcher in trench",
    "tiny gold-plated reclining mermaid statue",
    "green emerald that sparkles in sunlight",
    "gleaming sapphire hexagon perched on silver platter",
    "pink box of chocolates with strawberries and raspberries",
    "small wooden stool with blue cushion and white flowers",
    "flat-bladed rectangular shovel face",
    "green tea bag in cup steeping liquid"
]

start_time = time.time()

for idx, prompt in enumerate(DEFAULT_PROMPTS):
    loop_start_time = time.time()
    print(f"[{idx + 1}/{len(DEFAULT_PROMPTS)}][{time.time() - start_time:.2f}s] Generating image for prompt: '{prompt}'")

    # Optimize the prompt
    optimized_prompt = subprocess.run([
        "python", "optimize_prompt.py", f"--prompt={prompt}"
    ], capture_output=True, text=True).stdout.strip()

    print(f"[{idx + 1}/{len(DEFAULT_PROMPTS)}][{time.time() - start_time:.2f}s] Optimized prompt: '{optimized_prompt}'")

    time.sleep(2)

    result = subprocess.run([
        "python", "get_image.py", f"--prompt={optimized_prompt}", f"--filename_prefix=img_{idx + 1:03d}"
    ])
    if result.stderr:
        print(f"Error: {result.stderr}")
    print(f"[{idx + 1}/{len(DEFAULT_PROMPTS)}][{time.time() - start_time:.2f}s] Completed save image for prompt, take {time.time() - loop_start_time:.2f}s")
    print("")
    time.sleep(3)

print("Batch image generation complete.")
